---
title: "Gespräche (mit medien)"
author: "colomb_andother"
date: "24 Mar 2017"
output:
  slidy_presentation: default
---



# this document
Background für Gespräche mit Medien: Kernbotschaften und Zahlen
(Stand: 03. 03.2017)

Längere text version: 
https://github.com/jcolomb/marchforscience2017/documents/Background_Gespraeche_Medien.docx

# Marsch für Wissenschaft

## Weltweit und überparteilich

- Aktuell sind es 429 auf allen Kontinenten außer Antarktika. In Deutschland allein 15 Demos. https://www.marchforscience.com/satellite-marches/

- Wir sind bürger (nicht nur WissenschaftlerInnen) überparteilich und überinstitutionell. 

## Ziele und Geschichte


- Ziel ist gesellschaftliche Wichtigkeit von Wissenschaft zu verdeutlichen.

- Initialzündung war Proteste gegen Trumps. 

- Sind gegen „alternativen Fakten“, nicht nur in die USA, aber auch in Deutschland und Europa. 

## Aussage

- Wissenschaft und Forschung sind zentrale Säulen unserer offenen Demokratie.

- Forschung und Wissenschaft prägen unsere Gesellschaft.

- Deutschland Wirtschaft beruht auf exzellenter Wissenschaft, Forschung und Ausbildung.





# In Berlin

##Wer sind wir?

- Rd. 40  Personen 
- Bürger, u.a. Wissenschaftler und Künstler




## Die Marsch
- 22. April, 13h-15h

- Start: Humboldt-Univeristät Berlin, unter den linden 8

- End: Brandenburger Tor, mit podium

- inoffizielle Action ab 15h.

## Was brauchen wir

- Komm und marsch mit uns

- Wird supporter: http://marchforscienceberlin.de/supporters

- Finanzielle Unterstützung
